---

- name: setup runit for jenkins
  block:
    - name: create service directory tree
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop: "{{ jenkins_runit_directories }}"

    - template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: "{{ root_group }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: runit/run, dest: "{{ jenkins_runit_dir }}/run", mode: "0755" }
        - { src: runit/log/run, dest: "{{ jenkins_runit_log_dir }}/run", mode: "0755" }

    - name: link runit
      file:
        src: "{{ jenkins_runit_dir }}"
        dest: "{{ runit_services_dir }}/jenkins"
        state: link

  when: has_runit|d(false)


- name: setup standard service
  block:
    - fail:
        msg: "not implemented: setup standard service outside runit"

  when: not (has_runit|d(false))


- name: start standard service
  block:
    - name: enable standard FreeBSD service
      include: sysrc.yml key="{{ item.key }}" value="{{ item.value }}"
      loop: "{{ jenkins_services_sysrcs }}"
      when: ansible_system == 'FreeBSD'

    - name: enable standard Linux service
      service:
        name: "{{ item }}"
        enabled: true
      loop: "{{ jenkins_services }}"
      when: ansible_system == 'Linux'

    - service:
        name: "{{ item }}"
        state: started
      loop: "{{ jenkins_services }}"
      register: t_jenkins_service

    - service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ jenkins_services }}"
      when: t_jenkins_conf.changed and not t_jenkins_service.changed

  when: not (has_runit|d(false))
